// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB97ZLjBJRJqXxHyorBqtBD3keVVWNCC6o',
    appId: '1:189155336511:web:cf7ca95913982601b4b38a',
    messagingSenderId: '189155336511',
    projectId: 'push-notification-c508e',
    authDomain: 'push-notification-c508e.firebaseapp.com',
    storageBucket: 'push-notification-c508e.firebasestorage.app',
    measurementId: 'G-8EFEMZDHGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIWuUmXVCjSL1R3h8B1qvrsSblnxC8RG4',
    appId: '1:189155336511:android:177c8010b7311ee6b4b38a',
    messagingSenderId: '189155336511',
    projectId: 'push-notification-c508e',
    storageBucket: 'push-notification-c508e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAh7xg2nn1xL5jDGvkZ04vJZPRInrCVAs',
    appId: '1:189155336511:ios:6c21d068184834dcb4b38a',
    messagingSenderId: '189155336511',
    projectId: 'push-notification-c508e',
    storageBucket: 'push-notification-c508e.firebasestorage.app',
    iosBundleId: 'com.example.pushNotificationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAh7xg2nn1xL5jDGvkZ04vJZPRInrCVAs',
    appId: '1:189155336511:ios:6c21d068184834dcb4b38a',
    messagingSenderId: '189155336511',
    projectId: 'push-notification-c508e',
    storageBucket: 'push-notification-c508e.firebasestorage.app',
    iosBundleId: 'com.example.pushNotificationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB97ZLjBJRJqXxHyorBqtBD3keVVWNCC6o',
    appId: '1:189155336511:web:f71a7e79edaa4b4db4b38a',
    messagingSenderId: '189155336511',
    projectId: 'push-notification-c508e',
    authDomain: 'push-notification-c508e.firebaseapp.com',
    storageBucket: 'push-notification-c508e.firebasestorage.app',
    measurementId: 'G-SW2N9TLY37',
  );
}
